### funkcja generująca środowisko z pakietami żywnościowymi

In [1]:
function environment(n,m)
    Environment = zeros(Int64, n, m)
    for i in 2:3:n
        Environment[i,:] = ones(Int64, 1, m)
    end
    return Environment
end

environment (generic function with 1 method)

In [2]:
environment(20,20)

20×20 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1 

### funkcja determinująca przeżycie gołębia w trakcie ucieczki od jastrzębia (50% prawdopodobieństwa)

In [3]:
function golab_jastrzab(n_gol)
    if rand(0:1) == 0
        n_gol = n_gol - 1
    end
    return n_gol
end

golab_jastrzab (generic function with 1 method)

### funkcja determinująca stan populacji po wylosowaniu miejsc przy pakietach żywnościowych

In [4]:
#G-3
#J-8
function potyczki(n,m,macierz, g, ja)
    for i in 2:3:n, j in 1:m    
        suma = macierz[i-1,j] + macierz[i+1,j]
        if suma == 11
            g = golab_jastrzab(g)
            ja = ja + 1
        elseif suma == 6
            g = g
        elseif suma == 16 
            ja = ja - 2
        elseif suma == 3
            g += 2
        elseif suma == 8
            j += 2
        end 
    return g,ja
    end
end

potyczki (generic function with 1 method)

In [5]:
A = [3 3 8 8; 1 1 1 1; 3 3 3 8;
3 8 8 8; 1 1 1 1; 3 8 3 8]


6×4 Array{Int64,2}:
 3  3  8  8
 1  1  1  1
 3  3  3  8
 3  8  8  8
 1  1  1  1
 3  8  3  8

In [6]:
potyczki(6,4,A,8,8)


(8, 8)

In [7]:
B = [8 8 8 8 3;
1 1 1 1 1;
3 3 0 8 3;
3 3 3 8 8;
1 1 1 1 1;
8 8 0 3 3
]
#g = 10
#j = 11

6×5 Array{Int64,2}:
 8  8  8  8  3
 1  1  1  1  1
 3  3  0  8  3
 3  3  3  8  8
 1  1  1  1  1
 8  8  0  3  3

In [8]:
potyczki(6,4,B,9,10)

(9, 11)

### funkcja generująca rozstawienie ptaków w środowisku

In [57]:
function golabki(macierz, ngol)
    if ngol != 0  
        for i in 1:1:ngol
            z = findall(x -> x ==0, macierz)
            macierz[rand(z)] = 3
        end
    end
end
function jastrzabki(macierz, njas)
    if njas != 0
        for i in 1:1:njas
            z = findall(x -> x ==0, macierz)
            macierz[rand(z)] = 8
        end
    end
end

jastrzabki (generic function with 1 method)

In [58]:
mac = environment(21,21)
golabki(mac, 100)
jastrzabki(mac, 100)

In [59]:
test = environment(6,6)
golabki(test, 14)
jastrzabki(test, 10)
test

6×6 Array{Int64,2}:
 3  8  3  3  8  8
 1  1  1  1  1  1
 3  3  3  8  8  3
 3  8  3  8  8  3
 1  1  1  1  1  1
 3  3  3  3  8  8

In [60]:
mac

21×21 Array{Int64,2}:
 0  8  8  3  8  3  8  0  8  0  3  0  8  0  8  8  0  3  3  8  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  8  3  3  8  3  3  3  3  0  0  3  3  0  8  8  3  0  8  3  3
 3  0  8  0  3  0  0  0  3  0  8  8  3  0  8  3  3  3  0  8  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  8  3  3  3  8  0  8  3  0  8  8  8  0  8  0  8  3  3  8  8
 0  0  3  0  8  3  3  8  0  0  8  8  0  3  8  3  8  8  8  0  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  8  0  0  3  3  8  0  8  8  0  3  3  0  3  8  0  0  8  8  0
 3  3  3  8  8  8  8  8  8  8  8  3  0  8  8  3  0  0  3  0  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  3  3  3  8  0  0  0  3  3  8  3  0  8  0  8  8  0  0  0  3
 0  0  8  3  3  0  8  8  3  0  0  3  0  8  3  8  8  3  3  8  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  8  3  8  0  8  8  3  8  3  8  3  8  3  8  3  3  8  0  3  0
 0  3  3  8  3  8  8  0  3  8  0 

In [13]:
potyczki(21,21,mac,100,100)

(100, 98)

In [14]:
mac = environment(18,18)
golabki(mac, 70)
jastrzabki(mac, 90)

In [15]:
mac

18×18 Array{Int64,2}:
 8  8  3  8  0  3  8  3  8  3  0  3  3  0  8  3  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  3  0  3  3  8  8  8  8  8  8  8  8  8  0  3  3  8
 8  3  8  0  8  8  0  3  0  3  8  0  3  3  8  0  8  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  3  0  3  3  8  8  3  8  8  3  3  3  8  8  3  0
 3  8  0  0  3  8  0  0  3  8  8  3  3  8  3  8  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  8  0  0  8  0  8  3  0  3  8  3  3  0  0  3  8  0
 3  3  8  0  0  8  8  8  8  8  3  3  3  8  3  3  0  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  0  8  3  0  0  8  3  3  3  8  3  0  3  8  3  0  0
 0  8  0  3  0  0  0  3  3  8  8  8  0  8  8  0  8  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  8  8  8  8  0  3  0  3  0  8  8  8  8  0  3  3  3
 3  8  0  0  8  0  8  8  8  3  8  0  0  8  8  8  3  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  8  3  0  8  0  0  8  0  0  3  8  8  8  0  8  8  3

In [16]:
potyczki(18,18,mac,70,90)

(70, 90)

### funkcja sprawdzająca nadmiar populacji i ilość ptaków wysłaną na wygnanie/ fight club

funkcja/wątek do rozwinięcia

In [83]:
function check(n,m,ng, nja)
    if ng + nja > 2*n*m/3
        env_ng = Int64(round(ng/(ng+nja) * 2*n*m/3))
        env_ja = Int64(round(nja/(ng+nja) * 2*n*m/3))
        fight_g = ng - env_ng
        fight_ja = nja - env_ja
        ng = env_ng
        nja = env_ja
        return ng, nja, fight_g, fight_ja
    else
        fight_g = 0
        fight_ja = 0
        return ng, nja, fight_g, fight_ja
    end
end


check (generic function with 1 method)

In [84]:
check(9,9, 35,30)


(29, 25, 6, 5)

In [85]:
print(check(9,9,50,60))


(25, 29, 25, 31)

In [107]:
function fight_club(n_gol, n_jas)
    if (n_gol+n_jas)%2 == 0
        n = Int64((n_gol + n_jas)/2)
        M = zeros(Int64, 2, n)
        if n_gol != 0
            golabki(M,n_gol)
        end
        if n_jas!=0
            jastrzabki(M,n_jas)
        end
    else
        n = Int64((n_gol + n_jas + 1)/2) 
        M = zeros(Int64, 2, n)
        if n_gol != 0
            golabki(M,n_gol)
        end
        if n_jas!=0
            jastrzabki(M,n_jas)
        end
    end
    return M
end
        

fight_club (generic function with 1 method)

In [108]:
fight_club(3,3)

2×3 Array{Int64,2}:
 3  8  3
 3  8  8

In [115]:

function fight(macierz, n_gol, n_jas)
    for i in 1:size(macierz)[2]
        suma = macierz[1,i] + macierz[2,i]
        if suma == 6
            n_gol -= 1
        elseif suma == 16
            n_jas -= 1
        elseif suma == 11
            if rand(0:1) == 0
                n_gol -= 1
            else
                n_jas -= 1
            end
        end
    end
    return n_gol, n_jas
end

fight (generic function with 1 method)

In [116]:
fight(fight_club(3,3), 3, 3)

(1, 2)

### Generowanie środowiska z mniejszą ilością pakietów (na wypadek przykładowej suszy/ pożaru)


In [117]:
function environment_food_amount(size1 = 21, size2 = 21, amount = 100)
#ilość wieszy musi być podzielna przez 3
    if size1 % 3 != 0
        throw(DomainError(size, "incorrect size"))
    end
    Environment = zeros(Int64, size1, size2)
    A = zeros(Int64, 1, size2*(fld(size1-2,3)+1))
    A[1,1:amount] = ones(Int64, 1, amount)
    A = Random.shuffle(A)
    k = 1
    for i in 2:3:size1
        Environment[i,:] = A[1, k:(k+size1-1)]
        k += size1
    end
    return Environment
end

environment_food_amount (generic function with 4 methods)

In [118]:
function action(n, m, n_gol, n_jas, p)
    
    if p == 0
        return false
    end
    
    srod = environment(n,m) ##mamy pakiety
    
    a = check(n, m, n_gol, n_jas) #sprawdzamy czy nie ma za dużo ptaszków, zwraca jako (gol_safe, jas_safe, gol_fight, jas_fight)
    n_gol = a[1]
    n_jas = a[2]

    golabki(srod, n_gol)
    jastrzabki(srod, n_jas)  ##mamy srodowisko z ptaszkami
    
    result = potyczki(n,m,srod, n_gol, n_jas) ##mamy stan populacji po potyczkach
    n_gol = result[1] ##liczba gołębi
    n_jas = result[2]
    
    ##w miedzyczasie fight club :
    
    
    b = fight(fight_club(a[3],a[4]), a[3], a[4]) #populacja po fight clubie - (gol, jas)
    
    n_gol += b[1] ##ostateczna ilosc golebi - ta bezpieczna + fight club
    n_jas += b[2] ## -||- jastrzebi
    gol_fight = b[1] ##ilość ptakow po fightcie, może się przyda c:
    jas_fight = b[2]
    
    println(n_gol,",", n_jas,",", gol_fight, ",",jas_fight)
    
    action(n, m, n_gol, n_jas, p-1) #i lecimy rekurencją
end


action (generic function with 1 method)

In [125]:
action(9,9,30,30, 100)

29,28,2,1
29,25,2,0
29,26,0,0
29,27,1,0
28,28,0,1
27,29,0,1
26,30,0,1
25,30,1,0
25,31,0,1
23,32,0,1
23,30,0,1
23,31,0,0
23,29,0,0
23,27,0,0
22,28,0,0
22,29,0,0
22,27,0,0
24,27,0,0
24,28,0,0
24,28,0,0
23,29,0,0
23,30,0,0
23,31,0,0
23,29,0,0
23,29,0,0
23,27,0,0
25,27,0,0
25,28,0,0
24,29,0,0
24,27,0,0
23,28,0,0
23,26,0,0
23,24,0,0
23,22,0,0
25,22,0,0
25,23,0,0
24,24,0,0
24,24,0,0
24,24,0,0
23,25,0,0
22,26,0,0
22,27,0,0
22,25,0,0
21,26,0,0
21,27,0,0
21,27,0,0
21,27,0,0
21,25,0,0
20,26,0,0
19,27,0,0
18,28,0,0
18,29,0,0
17,30,0,0
17,31,0,0
17,31,0,0
17,31,0,0
16,32,0,0
16,30,0,0
18,30,0,0
18,28,0,0
17,29,0,0
16,30,0,0
15,31,0,0
17,31,0,0
17,29,0,0
17,27,0,0
17,25,0,0
16,26,0,0
15,27,0,0
15,27,0,0
14,28,0,0
14,26,0,0
14,26,0,0
14,24,0,0
13,25,0,0
13,25,0,0
13,25,0,0
12,26,0,0
12,24,0,0
12,24,0,0
12,22,0,0
12,23,0,0
14,23,0,0
16,23,0,0
16,24,0,0
16,24,0,0
16,25,0,0
16,23,0,0
16,23,0,0
16,23,0,0
18,23,0,0
17,24,0,0
16,25,0,0
16,26,0,0
16,24,0,0
16,25,0,0
16,25,0,0
16,26,0,0
16,26,0,0
16,26,0,0


false