### funkcja generująca środowisko z pakietami żywnościowymi

In [2]:
function environment(n,m)
    Environment = zeros(Int64, n, m)
    for i in 2:3:n
        Environment[i,:] = ones(Int64, 1, m)
    end
    return Environment
end

environment (generic function with 1 method)

In [3]:
environment(20,20)

20×20 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1 

### funkcja determinująca przeżycie gołębia w trakcie ucieczki od jastrzębia (50% prawdopodobieństwa)

In [4]:
function golab_jastrzab(n_gol)
    if rand(0:1) == 0
        n_gol = n_gol - 1
    end
    return n_gol
end

golab_jastrzab (generic function with 1 method)

### funkcja determinująca stan populacji po wylosowaniu miejsc przy pakietach żywnościowych

In [5]:
#G-3
#J-8
function potyczki(n,m,macierz, g, ja)
    for i in 2:3:n, j in 1:m    
        suma = macierz[i-1,j] + macierz[i+1,j]
        if suma == 11
            g = golab_jastrzab(g)
            ja = ja + 1
        elseif suma == 6
            g = g
        elseif suma == 16 
            ja = ja - 2
        elseif suma == 3
            g += 2
        elseif suma == 8
            j += 2
        end 
    println(g,ja)
    end
end

potyczki (generic function with 1 method)

In [6]:
A = [3 3 8 8; 1 1 1 1; 3 3 3 8;
3 8 8 8; 1 1 1 1; 3 8 3 8]


6×4 Array{Int64,2}:
 3  3  8  8
 1  1  1  1
 3  3  3  8
 3  8  8  8
 1  1  1  1
 3  8  3  8

In [7]:
potyczki(6,4,A,8,8)


88
88
89
87
87
85
86
84


In [8]:
B = [8 8 8 8 3;
1 1 1 1 1;
3 3 0 8 3;
3 3 3 8 8;
1 1 1 1 1;
8 8 0 3 3
]
#g = 10
#j = 11

6×5 Array{Int64,2}:
 8  8  8  8  3
 1  1  1  1  1
 3  3  0  8  3
 3  3  3  8  8
 1  1  1  1  1
 8  8  0  3  3

In [9]:
potyczki(6,4,B,9,10)

911
912
912
910
811
712
912
913


### funkcja generująca rozstawienie ptaków w środowisku

In [10]:
function golabki(macierz, ngol)
    for i in 1:1:ngol
        z = findall(x -> x ==0, macierz)
        macierz[rand(z)] = 3
    end
end
function jastrzabki(macierz, njas)
    for i in 1:1:njas
        z = findall(x -> x ==0, macierz)
        macierz[rand(z)] = 8
    end
end

jastrzabki (generic function with 1 method)

In [11]:
mac = environment(21,21)
golabki(mac, 100)
jastrzabki(mac, 100)

In [12]:
test = environment(6,6)
golabki(test, 14)
jastrzabki(test, 10)
test

6×6 Array{Int64,2}:
 3  8  3  8  3  3
 1  1  1  1  1  1
 3  3  3  3  3  8
 3  8  3  3  8  3
 1  1  1  1  1  1
 8  3  8  8  8  8

In [13]:
mac

21×21 Array{Int64,2}:
 8  8  0  8  3  0  3  8  0  8  8  3  0  3  0  3  0  0  0  0  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  0  8  0  8  0  3  8  0  3  8  0  3  0  8  3  3  8  0  8  3
 3  3  0  3  3  3  3  0  0  3  0  3  3  0  8  8  8  8  3  3  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  0  8  0  0  0  3  3  3  8  8  0  3  8  3  8  3  8  0  8
 8  8  8  3  0  3  3  3  8  0  8  3  8  3  0  8  3  3  0  3  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  8  8  0  8  0  0  0  0  8  0  3  8  0  0  3  8  8  3  0
 0  8  3  3  8  3  8  3  3  8  8  0  0  3  8  0  3  8  0  8  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  0  3  0  3  8  0  0  8  0  8  8  0  0  3  3  0  0  8  3
 8  8  8  3  8  8  3  3  8  3  8  3  0  8  3  3  3  0  0  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  8  3  0  8  8  3  0  8  8  8  3  3  3  8  3  8  8  0  8
 3  0  0  3  8  3  3  0  0  0  8 

In [14]:
potyczki(21,21,mac,100,100)

10098
10098
10098
10098
10099
10099
10099
10097
10097
9998
9996
10196
10396
10596
10596
10596
10796
10796
10796
10796
10796
10796
10796
10796
10797
10997
11197
11397
11597
11797
11797
11797
11698
11898
12098
12096
11997
11995
11996
11897
12097
12097
12098
11999
11997
11998
11998
11899
12099
12299
12299
12299
12297
12497
12398
12399
12399
12399
12399
123100
123100
123100
125100
127100
127101
129101
129101
129101
129101
12999
13199
13399
13397
13397
13397
13397
13597
13597
13797
13797
13797
13797
13795
13796
13796
13796
13794
13794
13794
13792
13793
13793
13793
13694
13692
13593
13793
13794
13794
13695
13695
13695
13695
13895
13893
14093
14093
14093
14094
14094
14294
14294
14294
14294
14494
14495
14695
14895
14895
14893
14893
14794
14794
14794
14994
14994
14992
15192
15190
15191
15189
15190
15188
15188
15188
15188
15189
15189
15189
15389
15290
15490
15391
15591
15791
15791
15791


In [15]:
mac = environment(18,18)
golabki(mac, 70)
jastrzabki(mac, 90)

In [16]:
mac

18×18 Array{Int64,2}:
 3  8  0  0  8  8  3  3  3  8  8  0  3  3  8  8  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  3  8  0  0  8  3  3  3  0  3  8  0  0  8  3  0  0
 8  8  8  3  8  3  3  3  3  0  3  3  0  0  3  0  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  3  8  3  0  0  8  3  8  3  8  0  3  3  0  3  0  0
 8  8  3  3  0  8  3  8  0  3  8  8  8  0  3  3  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  3  3  0  0  0  3  0  8  0  8  8  8  8  8  8  0  8
 8  0  8  8  3  3  8  3  8  8  8  0  0  8  3  8  8  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  3  8  0  0  3  0  3  8  3  8  8  3  0  0  8  3  3
 8  0  8  0  0  0  3  3  8  8  8  0  8  8  3  8  8  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  8  0  0  8  3  0  3  3  3  3  8  3  8  3  0  0  8
 0  0  8  3  8  8  3  8  8  0  0  8  3  3  3  8  8  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  0  8  8  8  0  3  8  8  3  8  3  3  8  8  3  8  0

In [17]:
potyczki(18,18,mac,70,90)

7290
7291
7291
7291
7291
7289
7289
7289
7289
7289
7190
7190
7390
7590
7588
7489
7689
7689
7687
7588
7586
7586
7586
7786
7787
7787
7788
7988
7989
8189
8389
8589
8789
8989
9189
9189
9187
9088
9088
9288
9288
9288
9288
9288
9288
9488
9486
9484
9482
9482
9483
9484
9684
9682
9680
9880
9878
9878
10078
10078
10078
10078
10076
10077
10075
10075
10275
10275
10475
10473
10474
10475
10473
10473
10473
10473
10473
10673
10873
10873
10774
10675
10676
10676
10577
10575
10575
10575
10575
10575
10575
10575
10573
10474
10472
10472
10472
10470
10468
10668
10668
10669
10669
10670
10671
10672
10670
10670


### funkcja sprawdzająca nadmiar populacji i ilość ptaków wysłaną na wygnanie/ fight club

funkcja/wątek do rozwinięcia

In [18]:
function check(n,m,ng, nja)
    if ng + nja > 2*n*m/3
        env_ng = Int64(round(ng/(ng+nja) * n*m))
        env_ja = Int64(round(nja/(ng+nja) * n*m))
        fight_g = ng - env_ng
        fight_ja = nja - env_ja
        ng = env_ng
        nja = env_ja
        return ng, nja, fight_g, fight_ja
    end
end


check (generic function with 1 method)

In [19]:
check(9,9, 50,60)


(37, 44, 13, 16)

In [20]:
gol_fight = check(9,9,50,60)[3]
jas_fight = check(9,9,50,60)[4]


16

In [21]:
function fight_club(n_gol, n_jas)
    if (n_gol+n_jas)%2 == 0
        n = Int64((n_gol + n_jas)/2)
        M = zeros(Int64, 2, n)
        golabki(M,n_gol)
        jastrzabki(M,n_jas)
    else
        n = Int64((n_gol + n_jas + 1)/2) 
        M = zeros(Int64, 2, n)
        golabki(M,n_gol)
        jastrzabki(M,n_jas)
    end
    M
end
        

fight_club (generic function with 1 method)

In [22]:
fight_club(9,10)

2×10 Array{Int64,2}:
 3  0  8  8  8  3  8  8  8  8
 3  3  8  3  3  3  3  8  3  8

In [23]:

function fight(macierz, n_gol, n_jas)
    for i in 1:size(macierz)[2]
        suma = macierz[1,i] + macierz[2,i]
        if suma == 6
            n_gol -= 1
        elseif suma == 16
            n_jas -= 1
        elseif suma == 11
            if rand(0:1) == 0
                n_gol -= 1
            else
                n_jas -= 1
            end
        end
    end
    return n_gol, n_jas
end

fight (generic function with 1 method)

In [26]:
fight(fight_club(9,10), 9, 10)

(4, 6)

### Generowanie środowiska z mniejszą ilością pakietów (na wypadek przykładowej suszy/ pożaru)


In [25]:
function environment_food_amount(size1 = 21, size2 = 21, amount = 100)
#ilość wieszy musi być podzielna przez 3
    if size1 % 3 != 0
        throw(DomainError(size, "incorrect size"))
    end
    Environment = zeros(Int64, size1, size2)
    A = zeros(Int64, 1, size2*(fld(size1-2,3)+1))
    A[1,1:amount] = ones(Int64, 1, amount)
    A = Random.shuffle(A)
    k = 1
    for i in 2:3:size1
        Environment[i,:] = A[1, k:(k+size1-1)]
        k += size1
    end
    return Environment
end

environment_food_amount (generic function with 4 methods)