In [2]:
function environment(n,m)
    Environment = zeros(Int64, n, m)
    for i in 2:3:n
        Environment[i,:] = ones(Int64, 1, m)
    end
    return Environment
end

environment (generic function with 1 method)

In [10]:
environment(20,20)

20×20 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1 

In [3]:
function golab_jastrzab(n_gol)
    if rand(0:1) == 0
        n_gol = n_gol - 1
    end
    return n_gol
end

golab_jastrzab (generic function with 1 method)

In [4]:
#G-3
#J-8
function potyczki(n,m,macierz, g, ja)
    for i in 2:3:n, j in 1:m    
        suma = macierz[i-1,j] + macierz[i+1,j]
        if suma == 11
            g = golab_jastrzab(g)
            ja = ja + 1
        elseif suma == 6
            g = g
        elseif suma == 16 
            ja = ja - 2
        elseif suma == 3
            g += 2
        elseif suma == 8
            j += 2
        end 
    println(g,ja)
    end
end

potyczki (generic function with 1 method)

In [23]:
A = [3 3 8 8; 1 1 1 1; 3 3 3 8;
3 8 8 8; 1 1 1 1; 3 8 3 8]


6×4 Array{Int64,2}:
 3  3  8  8
 1  1  1  1
 3  3  3  8
 3  8  8  8
 1  1  1  1
 3  8  3  8

In [24]:
potyczki(6,4,A,8,8)


88
88
79
77
77
75
76
74


In [25]:
B = [8 8 8 8 3;
1 1 1 1 1;
3 3 0 8 3;
3 3 3 8 8;
1 1 1 1 1;
8 8 0 3 3
]
#g = 10
#j = 11

6×5 Array{Int64,2}:
 8  8  8  8  3
 1  1  1  1  1
 3  3  3  8  3
 3  3  3  8  8
 1  1  1  1  1
 8  8  8  3  3

In [28]:
potyczki(6,4,B,9,10)

811
712
713
711
712
613
514
515


In [8]:
function golabki(macierz, ngol)
    for i in 1:1:ngol
        z = findall(x -> x ==0, macierz)
        macierz[rand(z)] = 3
    end
end
function jastrzabki(macierz, njas)
    for i in 1:1:njas
        z = findall(x -> x ==0, macierz)
        macierz[rand(z)] = 8
    end
end

jastrzabki (generic function with 1 method)

In [9]:
mac = environment(21,21)
golabki(mac, 100)
jastrzabki(mac, 100)

In [13]:
test = environment(6,6)
golabki(test, 14)
jastrzabki(test, 10)
test

6×6 Array{Int64,2}:
 3  3  3  3  8  8
 1  1  1  1  1  1
 8  8  3  3  8  8
 8  3  3  8  8  3
 1  1  1  1  1  1
 3  3  3  8  3  3

In [11]:
mac

21×21 Array{Int64,2}:
 0  3  3  0  8  8  0  0  8  0  0  8  0  8  3  0  3  3  3  0  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  8  3  8  8  8  0  0  3  3  0  0  0  0  3  8  3  3  3  3
 8  3  8  3  3  8  8  8  0  8  0  3  0  8  0  0  3  8  0  3  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  8  8  0  8  3  0  3  0  8  8  3  8  8  0  8  8  3  0  3  0
 0  0  3  8  8  3  0  8  8  0  3  3  8  0  0  8  8  8  3  8  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  3  3  0  3  3  0  8  3  0  8  0  8  8  3  3  3  8  3  0
 3  8  8  8  3  8  3  3  0  8  3  0  8  3  3  3  3  8  0  8  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  3  3  0  0  0  0  0  3  8  0  3  8  8  8  3  3  3  0  3
 8  0  0  8  3  8  0  0  3  8  3  8  3  0  8  3  0  0  3  0  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  8  8  8  8  8  3  3  3  0  3  8  8  0  0  8  0  8  8  3  8
 0  8  0  8  0  0  0  0  8  8  3 

In [45]:
potyczki(21,21,mac,100,100)

100100
100100
99101
99101
101101
101101
101101
101101
101101
103101
105101
105101
105101
105101
105101
107101
107101
107102
106103
106103
105104
105104
107104
109104
109104
109105
111105
113105
113105
113106
115106
115107
114108
114108
114109
113110
113110
113110
113110
113108
113108
113108
113108
115108
115109
117109
117109
119109
119109
119109
121109
121107
121107
121107
123107
123107
125107
125107
125107
125107
125105
127105
127105
129105
131105
133105
132106
134106
136106
136104
136104
138104
138104
138102
137103
137103
137101
137102
139102
138103
138103
138103
140103
140103
142103
144103
146103
146103
146103
146103
145104
147104
147104
147102
147102
149102
151102
150103
150103
152103
152103
152103
151104
153104
152105
152105
152105
152105
152105
151106
151106
153106
155106
155107
157107
157107
157107
157107
157107
157107
157105
157105
157105
159105
161105
163105
163105
162106
162106
162104
161105
161103
163103
162104
162104
162104
162104
162104
161105
161103
161101
161101
163101
1

In [48]:
mac = environment(18,18)
golabki(mac, 70)
jastrzabki(mac, 90)

In [49]:
mac

18×18 Array{Int64,2}:
 8  8  8  8  0  8  8  8  8  3  0  8  0  0  0  0  0  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  8  0  3  8  3  0  0  0  3  3  8  3  0  8  0  8  8
 3  0  8  8  8  0  0  8  0  8  8  8  3  0  8  8  3  3
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  8  8  8  0  8  3  3  3  8  8  3  3  0  0  8  0
 0  8  8  3  0  0  8  0  3  8  8  3  8  3  0  3  3  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  3  3  0  0  3  0  0  8  0  8  8  0  3  8  3  0  0
 3  3  8  3  0  3  8  3  8  8  0  0  8  8  0  3  3  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 8  0  8  3  8  3  0  3  0  3  0  3  0  0  3  0  0  8
 8  0  3  3  8  8  0  0  8  3  0  8  3  0  3  0  8  8
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  3  0  0  0  0  8  3  8  0  0  0  8  3  0  3  3  8
 0  0  8  8  0  8  0  3  0  0  8  0  0  3  3  0  0  0
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  3  3  0  3  0  0  3  8  8  0  3  8  0  8  3  3  3

In [50]:
potyczki(18,18,mac,70,90)

6991
6989
6989
6990
6990
6891
6891
6891
6891
6891
7091
7089
7289
7289
7289
7289
7289
7190
7390
7390
7388
7386
7384
7384
7384
7385
7585
7586
7584
7582
7582
7782
7782
7782
7783
7983
7983
7884
7885
8085
8085
8285
8285
8285
8186
8186
8184
8085
8085
8085
8085
8085
8285
8285
8186
8386
8384
8384
8384
8384
8384
8384
8384
8385
8385
8585
8585
8585
8785
8985
9185
9183
9183
9383
9583
9783
9783
9783
9783
9983
9981
10181
10181
10181
10182
10382
10582
10782
10783
10781
10781
10981
10982
10982
11182
11182
11182
11182
11182
11182
11182
11382
11382
11582
11483
11683
11883
12083


In [68]:
function check(n,m,ng, nja)
    if ng + nja > 2*n*m/3
        env_ng = Int64(round(ng/(ng+nja) * n*m))
        env_ja = Int64(round(nja/(ng+nja) * n*m))
        fight_g = ng - env_ng
        fight_ja = nja - env_ja
        return env_ng, env_ja, fight_g, fight_ja
    end
end


check (generic function with 1 method)

In [69]:
check(9,9, 50,60)


(37, 44, 13, 16)

In [70]:
Int64(3.0)

3

mamy 81 slotow
50 g, 60 j
wsp g = 50/110 * 81
wsp j = 60/110 * 81
